test/support/conn_case.ex:1: Unknown function 'Elixir.ExUnit.Callbacks':'__merge__'/4
test/support/conn_case.ex:1: Unknown function 'Elixir.ExUnit.Callbacks':'__noop__'/0
test/support/conn_case.ex:20: Unknown function 'Elixir.ExUnit.CaseTemplate':'__proxy__'/2
test/support/data_case.ex:1: Unknown function 'Elixir.ExUnit.Callbacks':'__merge__'/4
test/support/data_case.ex:1: Unknown function 'Elixir.ExUnit.Callbacks':'__noop__'/0
test/support/data_case.ex:21: Unknown function 'Elixir.ExUnit.CaseTemplate':'__proxy__'/2
test/support/data_case.ex:42: Unknown function 'Elixir.ExUnit.Callbacks':on_exit/1
